---
Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
  required:
    ':system_tests':
      - gem: beaker
        version: '~> 4'
        from_env: BEAKER_VERSION
      - gem: beaker-abs
        from_env: BEAKER_ABS_VERSION
        version: '~> 0.5'
      - gem: beaker-pe
      - gem: beaker-hostgenerator
        from_env: BEAKER_HOSTGENERATOR_VERSION
      - gem: beaker-rspec
        from_env: BEAKER_RSPEC_VERSION
      - gem: beaker-puppet
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.0'
      - gem: beaker-vmpooler
        from_env: BEAKER_PUPPET_VERSION
        version: '~> 1.3'
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
.travis.yml:
  delete: true
  global_env:
    - "---BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION=\"~> 5.0\""
    - BEAKER_PUPPET_COLLECTION=puppet6 PUPPET_GEM_VERSION="git://github.com/puppetlabs/puppet#master"

Rakefile:
  changelog_version_tag_pattern: '%s'
  extras: |
    desc "verify that commit messages match CONTRIBUTING.md requirements"
    task(:commits) do
      # This rake task looks at the summary from every commit from this branch not
      # in the branch targeted for a PR.
      commit_range = 'HEAD^..HEAD'
      puts "Checking commits #{commit_range}"
      %x{git log --no-merges --pretty=%s #{commit_range}}.each_line do |commit_summary|
        # This regex tests for the currently supported commit summary tokens.
        # The exception tries to explain it in more full.
        if /^\((maint|packaging|doc|docs|modules-\d+)\)|revert/i.match(commit_summary).nil?
          raise "\n\n\n\tThis commit summary didn't match CONTRIBUTING.md guidelines:\n" \
            "\n\t\t#{commit_summary}\n" \
            "\tThe commit summary (i.e. the first line of the commit message) should start with one of:\n"  \
            "\t\t(MODULES-<digits>) # this is most common and should be a ticket at tickets.puppet.com\n" \
            "\t\t(docs)\n" \
            "\t\t(docs)(DOCUMENT-<digits>)\n" \
            "\t\t(packaging)\n"
            "\t\t(maint)\n" \
            "\n\tThis test for the commit summary is case-insensitive.\n\n\n"
        else
          puts "#{commit_summary}"
        end
        puts "...passed"
      end
    end
